function ItemsFixe() {
  return (
    <div className="py-8">
      <div
        className="
      w-full 
      mb-6 
      mt-6
      "
      ></div>
      <div
        className="
      flex 
      justify-center
      "
      >
        <div
          className="
          w-[83%] 
          h-px 
          bg-[#A9AFBB]
          mb-10
          "
        ></div>
      </div>
      <div
        className="
        flex 
        justify-around 
        text-center
        "
      >
        <div
          className="
          flex 
          items-center
          "
        >
          <h3
            className="
            text-3xl 
            font-bold 
            font-kaushan 
            mr-4
            "
          >
            120+
          </h3>
          <p
            className="
            font-inter 
            text-sm
            "
          >
            Total Destination
          </p>
        </div>
        <div
          className="
          flex 
          items-center
          "
        >
          <h3
            className="
            text-3xl 
            font-bold 
            font-kaushan 
            mr-4
            "
          >
            500+
          </h3>
          <p
            className="
            font-inter 
            text-sm
            "
          >
            Travel Package
          </p>
        </div>
        <div
          className="
          flex 
          items-center
          "
        >
          <h3
            className="
            text-3xl 
            font-bold 
            font-kaushan 
            mr-4
            "
          >
            12k+
          </h3>
          <p
            className="
            font-inter 
            text-sm
            "
          >
            Total Travelers
          </p>
        </div>
        <div
          className="
          flex 
          items-center
          "
        >
          <h3
            className="
            text-3xl 
            font-bold 
            font-kaushan 
            mr-4
            "
          >
            7k+
          </h3>
          <p
            className="
            font-inter 
            text-sm
            "
          >
            Positive Reviews
          </p>
        </div>
      </div>
    </div>
  );
}

export default ItemsFixe;
