import { CiLogin, CiSearch } from "react-icons/ci";

const Header = () => {
  return (
    <header className="bg-white">
      <div
        className="
        flex
        justify-between
        items-center
        font-work-sans
      "
      >
        <div
          className="
          flex
          items-center
          ml-8
        "
        >
          <img
            src="https://mybucketomyproject.s3.us-east-2.amazonaws.com/logo.png"
            alt="Logo"
            className="
            h-20
          "
          />
        </div>

        <nav
          className="
          flex-1
          ml-14
        "
        >
          <ul
            className="
            flex
            space-x-8
            text-gray-700
            font-medium
          "
          >
            <li>
              <a
                href="#home"
                className="
                text-red-500
                hover:text-red-700
              "
              >
                Home
              </a>
            </li>
            <li>
              <a
                href="#about"
                className="
                hover:text-red-500
              "
              >
                About
              </a>
            </li>
            <li>
              <a
                href="#tours"
                className="
                hover:text-red-500
                "
              >
                Tours
              </a>
            </li>
            <li>
              <a
                href="#destination"
                className="
                hover:text-red-500
              "
              >
                Destination
              </a>
            </li>
            <li>
              <a
                href="#blog"
                className="
                hover:text-red-500
              "
              >
                Blog
              </a>
            </li>
            <li>
              <a
                href="#pages"
                className="
                hover:text-red-500
              "
              >
                Pages
              </a>
            </li>
            <li>
              <a
                href="#contact"
                className="
                hover:text-red-500
              "
              >
                Contact
              </a>
            </li>
          </ul>
        </nav>

        <div
          className="
          flex
          items-center
          space-x-4
          mr-14
        "
        >
          <button
            className="
            transform
            transition-transform
            duration-300
            ease-in-out
            hover:-translate-y-1
          "
          >
            <CiSearch size={20} />
          </button>

          <a
            href="./signin"
            className="
            grid
            gap-2
            grid-flow-col
            transform
            transition-transform
            duration-300
            ease-in-out
            hover:-translate-y-1
          "
          >
            <CiLogin size={20} />
            Login
          </a>
          <span>/</span>
          <a
            href="./signup"
            className="
            transform
            transition-transform
            duration-300
            ease-in-out
            hover:-translate-y-1
          "
          >
            SignUp
          </a>
        </div>
      </div>
    </header>
  );
};

export default Header;
